# Site settings

title: Cade Conradson
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Put something here eventually
baseurl: "" # the subpath of your site, e.g. /blog
url: https://cconradson.github.io # the base hostname & protocol for your site, e.g. http://example.com
github_username:  cconradson

# Build settings
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
